### ISSUE TITLE
Move in stuff from gfx-rs

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/draw_state#1]
Should copy from

https://github.com/gfx-rs/gfx-rs/blob/master/src/device/state.rs

https://github.com/gfx-rs/gfx-rs/blob/master/src/render/state.rs

**Comment by bvssvni** [comment]
I'll do this!

**Comment by kvark** [comment]
:+1: please keep it in several sub-modules though, don't mix up the device ones with `DrawState` as a whole
