### ISSUE TITLE
Add helper methods for 2D clipping using stencil buffer?

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/draw_state#14]
Assume you want to rendering something inside an ellipse. Or, you might want to render something, but not inside an ellipse. You would then render to the stencil buffer while disabling the frame buffer, and then render to the frame buffer while testing with the stencil buffer.

It would be nice to have some helper methods for changing the draw state when clipping in 2D:
- `stencil_clip` (render to stencil buffer, disable frame buffer)
- `clip_inside` (enable frame buffer, check stencil buffer for "inside")
- `clip_outside` (enable frame buffer, check stencil buffer for "outside")

**Comment by kvark** [comment]
This seems to be higher-level functionality, no need to shove it into `draw_state`.

**Comment by bvssvni** [comment]
You are probably right.
