### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/draw_state#3]
Need it to update piston-graphics.

**Comment by kvark** [comment]
In the worst case, I'll publish it tonight.

**Comment by brendanzab** [comment]
Can't do it until tonight (AUEST)

**Comment by kvark** [comment]
EST, PST, AUEST, MST, ... Why isn't there a common standard? Oh wait...

**Comment by brendanzab** [comment]
Oh, probs should be AEST. ie. Australian Eastern Standard Time.

**Comment by bvssvni** [comment]
I can do it and add rest of you as owners.

**Comment by bvssvni** [comment]
Done https://crates.io/crates/draw_state
