### ISSUE TITLE
Update to new version of bitflags

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/draw_state#37]
Can wait until Gfx 0.10.0.

This is a breaking change, so it can be bumped to 0.4.0.

**Comment by kvark** [comment]
Out of curiosity, why do you need gfx 0.10?

**Comment by bvssvni** [comment]
@kvark I meant wait right before publishing gfx 0.10, so we don't have to update it twice.

**Comment by kvark** [comment]
Thanks, noted in https://github.com/gfx-rs/gfx/issues/852
