### ISSUE TITLE
Rename "block" to "state"

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/draw_state#4]
Decision: Rename "block" to "state".

The name suggests "building block" or something which is a bit too generic for my taste.

Suggestions?

**Comment by bvssvni** [comment]
Some ideas:
- settings
- ops
- config

**Comment by bvssvni** [comment]
I kind of like the name "ops".

**Comment by kvark** [comment]
Maybe just `state`?

**Comment by bvssvni** [comment]
Yeah, `state` would be fine.
